Repository CheesecakeLabs/stellar-plus, pull requests merged in 2024-04, with the labels that each got.

#115 test: add unit tests for classic signature requirements pipeline
  src/stellar-plus/core/pipelines/classic-sign-requirements/index.ts
  src/stellar-plus/core/pipelines/classic-sign-requirements/index.unit.test.ts
Labels: enhancement

#117 Add unit tests for simulate transaction pipeline
  src/stellar-plus/core/pipelines/classic-sign-requirements/index.unit.test.ts
  src/stellar-plus/core/pipelines/simulate-transaction/errors.ts
  src/stellar-plus/core/pipelines/simulate-transaction/index.ts
  src/stellar-plus/core/pipelines/simulate-transaction/index.unit.test.ts
Labels: enhancement

#118 Add unit tests for classic transaction pipeline
  src/stellar-plus/core/pipelines/classic-transaction/index.ts
  src/stellar-plus/core/pipelines/classic-transaction/index.unit.test.ts
Labels: enhancement

#119 Add unit tests for soroban transaction pipeline
  src/stellar-plus/core/pipelines/soroban-transaction/index.unit.test.ts
Labels: enhancement

#120 test: add unit test for sign transaction pipeline
  src/stellar-plus/core/pipelines/sign-transaction/errors.ts
  src/stellar-plus/core/pipelines/sign-transaction/index.ts
  src/stellar-plus/core/pipelines/sign-transaction/index.unit.test.ts
  src/stellar-plus/test/mocks/transaction-mock.ts
Labels: enhancement

#122 test: add unit test for submit transaction pipeline
  src/stellar-plus/core/pipelines/submit-transaction/index.ts
  src/stellar-plus/core/pipelines/submit-transaction/index.unit.test.ts
Labels: enhancement

#123 Add unit tests soroban auth
  src/stellar-plus/core/contract-engine/index.ts
  src/stellar-plus/core/contract-engine/index.unit.test.ts
  src/stellar-plus/core/pipelines/sign-transaction/index.unit.test.ts
  src/stellar-plus/core/pipelines/soroban-auth/index.ts
  src/stellar-plus/core/pipelines/soroban-auth/index.unit.test.ts
  src/stellar-plus/test/mocks/transaction-mock.ts
Labels: enhancement

#125 Complete unit test coverage for account handlers
  src/stellar-plus/account/account-handler/default/index.unit.test.ts
  src/stellar-plus/account/account-handler/freighter/freighter.test.ts
  src/stellar-plus/account/account-handler/freighter/index.ts
  src/stellar-plus/account/account-handler/freighter/index.unit.test.ts
Labels: enhancement

#126 Create test-coverage.yml action
  .github/workflows/test-coverage.yml
Labels: enhancement

#124 Add unit test for soroban get transaction pipeline
  src/stellar-plus/core/pipelines/soroban-get-transaction/index.ts
  src/stellar-plus/core/pipelines/soroban-get-transaction/index.unit.test.ts
  src/stellar-plus/core/pipelines/soroban-get-transaction/types.ts
  src/stellar-plus/core/pipelines/soroban-transaction/index.ts
  src/stellar-plus/core/pipelines/soroban-transaction/index.unit.test.ts
  src/stellar-plus/error/helpers/result-meta-xdr.ts
Labels: enhancement

#128 Add unit tests for the classic asset handler
  src/stellar-plus/asset/classic/index.ts
  src/stellar-plus/asset/classic/index.unit.test.ts
  src/stellar-plus/constants.ts
  src/stellar-plus/types.ts
Labels: enhancement

#129 feat: remove issuer requirement for classic assets
  src/stellar-plus/account/account-handler/default/index.ts
  src/stellar-plus/asset/classic/index.ts
  src/stellar-plus/asset/classic/index.unit.test.ts
  src/stellar-plus/asset/classic/types.ts
Labels: classic

#132 feat: remove helper classes for account
  src/stellar-plus/account/account-handler/default/index.ts
  src/stellar-plus/account/account-handler/freighter/index.ts
  src/stellar-plus/account/account-handler/types.ts
  src/stellar-plus/account/base/errors.ts
  src/stellar-plus/account/base/index.ts
  src/stellar-plus/account/base/index.unit.test.ts
  src/stellar-plus/account/base/types.ts
  src/stellar-plus/account/helpers/account-data-viewer/index.ts
  src/stellar-plus/account/helpers/account-data-viewer/types.ts
  src/stellar-plus/account/helpers/friendbot/index.ts
  src/stellar-plus/account/helpers/friendbot/types.ts
  src/stellar-plus/account/helpers/index.ts
  src/stellar-plus/account/helpers/types.ts
  src/stellar-plus/account/index.ts
  src/stellar-plus/error/types.ts
  src/stellar-plus/test/mocks/transaction-mock.ts
Labels: feature
